language: node_js
node_js:
 - 16.3.0
before_install:
 - npm i -g npm@7.15.1
 cache: npm
 env:
  - CXX=g++-4.8
  addons:
   apt:
    sources: 
     - ubuntu-toolchain-r-test
    packges:
     - g++-4.8
